name: Feature Request
description: Request a new feature or enhancement for weaviate-cli
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please fill in the sections below. If this issue was created by an AI agent,
        all fields should be populated with structured context.

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What problem does this solve? Why is this needed?
      placeholder: Describe the motivation and use case.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What specifically needs to change or be added?
      placeholder: |
        - Add `weaviate-cli create widget` command
        - Support --name, --size, --enabled flags
        - Add --json output
    validations:
      required: true

  - type: textarea
    id: files-involved
    attributes:
      label: Files Involved
      description: Key files and modules that will need changes.
      placeholder: |
        - weaviate_cli/commands/create.py
        - weaviate_cli/managers/widget_manager.py
        - weaviate_cli/defaults.py
        - test/unittests/test_managers/test_widget_manager.py

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Command works with default arguments
        - [ ] --json flag produces structured output
        - [ ] Unit tests cover happy path and error cases
        - [ ] `make lint` passes
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: What should NOT change? Any patterns to follow or avoid?
      placeholder: |
        - Follow existing defaults.py dataclass pattern
        - Don't modify existing tests
        - Must support Python 3.9+

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or references.
